name: "Gradle"
description: "Initialize Java and do Gradle Stuff!"
inputs:
  arguments:
    description: "Gradle Arguments"
    required: true
  github_token:
    description: "secrets.GITHUB_TOKEN, for publishing"
    required: true
  gradle_version:
    description: "Which Gradle version to use"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Do Gradle Things
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: ${{ inputs.arguments }}
        gradle-version: ${{ inputs.gradle_version }}
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ inputs.github_token }}
